plugin {
    hyprbars {
        bar_height = 40

        bar_color = rgb(32, 32, 32)

        bar_text_font = SauceCodePro Nerd Font

        bar_text_size = 12

        bar_button_padding = 8

        # bar_padding = 10

        show_window_icon = false

        bar_bloor = false

        bar_part_of_window = true

        bar_buttons_alignment = left

        bar_precedence_over_border = true

        icon_on_hover = true

        hyprbars-button = rgb(ff5f57), 14, 󰖭, hyprctl dispatch killactive

        hyprbars-button = rgb(fdbc40), 14, 󰖰, hyprctl dispatch movetoworkspacesilent special

        hyprbars-button = rgb(28c840), 14, , /home/saiddis/.config/hypr/scripts/toggle-float.sh

        on_double_click = /home/saiddis/.config/hypr/scripts/toggle-float.sh
    }
}

