$mainMod = ALT 
$TERMINAL = ghostty
$BROWSER = qutebrowser

source = ./env.conf
source = ./monitors.conf
source = ./windowrules.conf
source = ./keybindings.conf
source = ./userprefs.conf
source = ./animations/vertical.conf
source = ./nvidia.conf
# source = ./pypr.conf

exec-once = hyprpm reload
exec-once = hyprctl setcursor $HYPRCURSOR_THEME $HYPRCURSOR_SIZE
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = hyprpaper & hyprsunset & hypridle
exec-once = systemctl --user start hyprpolkitagent 
exec-once = /home/saiddis/go/bin/hyprpanel
exec-once = blueman-applet & nm-applet --indicator & syshud -p bottom-left -o v

exec-once = foot --server -c $XDG_CONFIG_HOME/foot/foot.ini

bind = ALT, TAB, exec, $HOME/.config/hypr/scripts/alttab/enable.sh 'down'
bind = ALT SHIFT, TAB, exec, $HOME/.config/hypr/scripts/alttab/enable.sh 'up'

submap=alttab
bind = ALT, tab, sendshortcut, , tab, class:alttab
bind = ALT SHIFT, tab, sendshortcut, shift, tab, class:alttab

bindrt = ALT, ALT_L, exec, $XDG_CONFIG_HOME/hypr/scripts/alttab/disable.sh ; hyprctl -q dispatch sendshortcut , return,class:alttab
bindrt = ALT SHIFT, ALT_L, exec, $XDG_CONFIG_HOME/hypr/scripts/alttab/disable.sh ; hyprctl -q dispatch sendshortcut , return,class:alttab
bind = ALT, Return, exec, $XDG_CONFIG_HOME/hypr/scripts/alttab/disable.sh ; hyprctl -q dispatch sendshortcut , return, class:alttab
bind = ALT SHIFT, Return, exec, $XDG_CONFIG_HOME/hypr/scripts/alttab/disable.sh ; hyprctl -q dispatch sendshortcut , return, class:alttab
bind = ALT, escape, exec, $XDG_CONFIG_HOME/hypr/scripts/alttab/disable.sh ; hyprctl -q dispatch sendshortcut , escape,class:alttab
bind = ALT SHIFT, escape, exec, $XDG_CONFIG_HOME/hypr/scripts/alttab/disable.sh ; hyprctl -q dispatch sendshortcut , escape,class:alttab
submap = reset

workspace = special:alttab, gapsout:0, gapsin:0, bordersize:0, rounding:0
windowrule = match:class alttab, no_anim on
windowrule = match:class alttab, stay_focused on
windowrule = match:class alttab, workspace special:alttab
windowrule = match:class alttab, border_size 0
